name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Verify Java Version
      run: java -version

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: List all directories and subdirectories
      run: find . -type d

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: List directory contents
      run: ls -la

    - name: Build Debug APK and AAB
      run: |
        ./gradlew assembleDebug
        ./gradlew bundleDebug

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
