name: Build Unity Project (APK)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          echo "## Unity License" >> $GITHUB_ENV
          echo $UNITY_LICENSE >> $GITHUB_ENV
          

      - name: Install Unity
        uses: sean-l/unity-setup-action@v1  # Or alternative caching approach
        with:
          unity-version: '2023.2.0f1'  # Update with your desired version

      - name: Build APK (replace with your build arguments)
        run: |
          unity -batchmode -quit -projectPath path/to/your/project.unityproj -buildTarget Android -exportPath Builds/Android
          # You might need to configure additional arguments like keystore details
