name: Unity Build

on: [push]  # Triggers the workflow on push events to any branch

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Cache Unity Libraries
      uses: actions/cache@v2
      with:
        path: Library
        key: ${{ runner.os }}-library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
        restore-keys: |
          ${{ runner.os }}-library-

    - name: Setup Unity
      uses: game-ci/unity-request-activation-file@v2  # This action is part of the Game CI community
      with:
        unityVersion: '2020.3.0f1'  # Specify your Unity version here

    - name: Build Project
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: '2020.3.0f1'
        targetPlatform: StandaloneWindows64  # Define your build platform

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build/windows  # Adjust path according to your build output
