name: Build Unity Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          echo "## Unity License" >> $GITHUB_ENV
          echo $UNITY_LICENSE >> $GITHUB_ENV
          

      - name: Install Unity
        uses: sean-l/unity-setup-action@v1
        with:
          unity-version: '2023.2.0f1'

      - name: Load project
        uses: gitpodhq/unity-actions@v1
        with:
          project: path/to/your/project.unityproj

      - name: Build Project (replace with your build command)
        run: |
          unity -batchmode -quit -projectPath path/to/your/project.unityproj -buildTarget StandaloneWindows64 -exportPath Builds/Windows
          # Replace with your specific build target and output path