name: Build Unity Project (APK)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Unity Editor
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: '2020.3.25f1'
        targetPlatform: StandaloneWindows64

    - name: Activate Unity License
      uses: game-ci/unity-activate@v2
      with:
        unityVersion: '2020.3.25f1'
        license: ${{ secrets.UNITY_LICENSE }}

    - name: Build Project
      run: |
        echo "Building Unity Project"
        unity -batchmode -nographics -silent-crashes -logFile -projectPath "$(pwd)" -buildWindows64Player "$(pwd)/Build/game.exe" -quit
