name: Build Unity APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/setup-unity@v1
      with:
        unityVersion: 2020.3.17f1
        modules: android
        license: ${{ secrets.UNITY_LICENSE }}

    - name: Build Unity Project
      run: |
        mkdir Builds
        unity-build -quit -batchmode -projectPath YourUnityProjectName -buildTarget Android -executeMethod BuildScript.PerformBuild -logFile Builds/build.log
        ls -lR Builds

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: YourUnityProjectName-APK
        path: Builds/*.apk
