name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Unity packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/unity3d
          ~/Library/Unity
        key: ${{ runner.os }}-unity-${{ hashFiles('**/Packages/manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-unity-

    - name: Activate Unity License
      uses: game-ci/unity-activate@v4
      with:
        unityEmail: ${{ secrets.UNITY_EMAIL }}
        unityPassword: ${{ secrets.UNITY_PASSWORD }}
        licenseFile: ${{ secrets.UNITY_LICENSE }}

    - name: Build Android
      uses: game-ci/unity-builder@v4
      with:
        unityVersion: 2022.3.20f1
        targetPlatform: Android
        projectPath: .

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build/Android/*.apk
