name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Unity Hub
        uses: game-ci/unity-hub@v2
        with:
          unityVersion: 2020.3.30f1
          unityModules: android

      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

      - name: Build Android
        run: |
          export UNITY_PROJECT_PATH=$(pwd)
          export BUILD_SCRIPT_PATH=$UNITY_PROJECT_PATH/Assets/Editor/BuildScript.cs
          unity-editor -projectPath $UNITY_PROJECT_PATH -executeMethod BuildScript.BuildAndroid -quit -batchmode -nographics

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: Builds/Android/MyGame.apk
