jobs:
  activate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Request manual activation file
        id: request-license
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: '2020.3.0f1' # Replace with your Unity version

      - name: Save manual activation file
        uses: actions/upload-artifact@v2
        with:
          name: UnityActivationFile.alf
          path: ${{ steps.request-license.outputs.filePath }}

      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        with:
          licenseFile: ${{ secrets.UNITY_LICENSE_XML }} # This should be a Base64 encoded XML license file

      # After successful activation, you can proceed with the build
      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          projectPath: .
          targetPlatform: WebGL # Example target platform
          unityVersion: '2020.3.0f1' # Make sure this matches the version used for activation

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
