name: Build Unity Project (APK)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Activate Unity License
      uses: game-ci/unity-activate@v2
      with:
        unityVersion: '2020.3.25f1'  # Specify your Unity version
        unityEmail: ${{ secrets.UNITY_EMAIL }}
        unityPassword: ${{ secrets.UNITY_PASSWORD }}
        unityLicense: ${{ secrets.UNITY_LICENSE }}

    - name: Build Unity Project
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: '2020.3.25f1'  # Ensure this matches the activation step
        targetPlatform: StandaloneWindows64  # Specify your target platform